<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Standard;

class StandardSeeder extends Seeder
{
    public function run(): void
    {
        $standards = [
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'AQUASPRING 350 x24', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 1165, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'AQUASPRING 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'AQUASPRING 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'FISHERMALL500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'GO FRESH 350 x35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'GOFRESH 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'MAGICSAVER 350 X35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'MAGICSAVER 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE  520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'MAGICSAVER 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'PREMIER 350', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'PREMIER 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'PREMIER 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'RIDE REVOLUTION 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS White Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'SAILUN 350 x35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'SIP 350 x24', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 1165, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'SIP 350 x35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'SIP 350 5+1', 'bottles_per_case' => 6, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 320 mm', 'cases_per_roll' => 1587, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'SIP 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'SIP 500 5+1', 'bottles_per_case' => 6, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 320 mm', 'cases_per_roll' => 1428, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'SIP 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly Blue', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'SADDLE ROW 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE  520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'Sticker Label', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'SUREBUY 350 x35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'SUREBUY 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'SUREBUY 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => ' LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'BC Sticker Double', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'THE SMILE BAR 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label China', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '350 ml', 'description' => 'WESTCOAST 350 x 35', 'bottles_per_case' => 35, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => 'LDPE 560 mm', 'cases_per_roll' => 819, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label Shrinkpack', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '500 ml', 'description' => 'WESTCOAST 500', 'bottles_per_case' => 24, 'preform_weight' => 'PREFORM 11/12 gms.', 'ldpe_size' => ' LDPE 520 mm', 'cases_per_roll' => 803, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label Shrinkpack', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.011, 'preform_weight2' => 0.011],
            ['group' => 'Water', 'mat_no' => 'n/a', 'size' => '1 li', 'description' => 'WESTCOAST 1L', 'bottles_per_case' => 12, 'preform_weight' => 'PREFORM 21 gms.', 'ldpe_size' => 'LDPE 480 mm', 'cases_per_roll' => 900, 'caps' => 'CAPS Manly White', 'opp_label' => 'OPP Label Shrinkpack', 'barcode_sticker' => 'None', 'alt_preform_for_350ml' => 0.021, 'preform_weight2' => 0.021],
        ];

        foreach ($standards as $standard) {
            Standard::create($standard);
        }
    }
}
