runtime: php
env: flex

runtime_config:
  document_root: public

handlers:
  - url: /.*
    script: auto

env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: "base64:XWXsyibBXw1zTjpiQsDlgWPkG5NUusJI9d11/AwOLDk="
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  LOG_CHANNEL: stderr
